services:
  myportofolio:
    build: .
    networks:
      - ternasys
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
#    ports:
#      - "80:80"

networks:
  ternasys:
      name: nginx-proxy_network
      external: true